apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl (printf "%s-config" .Release.Name) . | lower | quote }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env.keys }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}