namespace: default

appName: frontend-app-vite

replicas: 0

port: 3000

service:
  port: 3000
  targetPort: 3000
  protocol: TCP
  type: LoadBalancer

image:
  name: vunguyen88/todo-openshift-client
  tag: latest
  pullPolicy: IfNotPresent

env:
  configMapName: app-config
  keys:
    VITE_API_URL: "https://api.default.com"
    VITE_ENV: "default"