namespace: default

appName: frontend-app-vite

replicas: 1

port: 3000

service:
  port: 3000
  targetPort: 3000
  protocol: TCP
  type: LoadBalancer

image:
  name: vunguyen88/todo-openshift-client
  tag: latest
  pullPolicy: Always